config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" }
  resources :users, only: %w[index show update ]

  root to: 'cities#home'

  resources :cities, only: %w[new create edit update]
  resources :cities, only: %w[show] do 
    resources :events, only: %w[index new create]
    resources :faq, only: %w[index]
    resources :events, only: %w[index show]
    resources :headlines, only: %w[index]
    resources :chatrooms, only: :show
    resources :forums, only: %w[] do 
      resources :posts, only: %w[index]
    end 
  end
  resources :forums, only: [] do 
    resources :posts, only: %w[create]
  end 
  resources :posts, only: %w[destroy] do 
    resources :comments, only: %w[create]
  end 
  resources :chatrooms, only: [] do
    resources :messages, only: %w[create]
  end 
  resources :locations, only: %w[index]
end

app/views/shared/_flashes.html.erb
<% if notice %>
<div class="alert alert-info alert-dismissible fade show m-1" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>
<% if alert %>
<div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
  <%= alert %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-dark text-center text-lg-start main-footer" style="background-color: #167FFB"> 
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    <span class="text-white">Coded with ❤️ in Lisbon by </span>
    <a class="text-white" href="https://github.com/ThorOnTheRocks" target="_blank">Gianluca, </a>
    <a class="text-white" href="https://github.com/Fujanetti" target="_blank">Giuseppe, </a>
    <a class="text-white" href="https://github.com/jderen123" target="_blank">Jordan </a> <span class="text-white"> and </span>
    <a class="text-white" href="https://github.com/thales-gomes" target="_blank">Thales</a>
  </div>
 </footer>

app/views/shared/_navbar.html.erb
<nav class="navbar bg-dark navbar-expand-sm">
  <%= link_to "NomadConnect", root_path, class: "navbar-brand w-25" %>
  <%# Middle nav buttons %>
  <div class="navbar-nav w-auto mx-auto">
    <% if @city %>
      <%= link_to @city.name, city_path(@city), class: "#{navbar_active("cities")} nav-item nav-link nav-current-city" %>
      <%= link_to "Discussion", city_forum_posts_path(@city, @city.forums.first), class: "#{navbar_active("posts")} nav-item nav-link"%>
      <%= link_to "Events", city_events_path(@city), class: "#{navbar_active("events")} nav-item nav-link" %>
      <%= link_to "News", city_headlines_path(@city), class: "#{navbar_active("headlines")} nav-item nav-link" %>
      <%= link_to "FAQ", city_path(@city), class: "nav-item nav-link" %>
    <% end %>
  </div>

  <%# Avatar button %>
  <div class="navbar-nav w-25 justify-content-end mb-0">
    <%= link_to "Cities", root_path, class: "nav-item nav-link my-auto mr-1" %>
    <% if user_signed_in? %>
      <%= link_to current_user.username, user_path(current_user), data: {current_user: current_user.id}, class: "nav-item nav-link my-auto mr-0 nav-username"%>  
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "nav-item nav-link my-auto mr-1"%>  
    <% end %>

    <div class="dropdown">    
      <%= link_to "#", class: "nav-item nav-link dropdown-toggle navbar-avatar nav-drop-style ml-0", id: "profileDropdown", data: {toggle: "dropdown"}, "aria-haspopup": true, "aria-expanded": false do%>
        <% user_photo = get_photo_key(current_user)  %>
        <%= cl_image_tag user_photo, crop: :thumb, gravity: :face, class: "avatar ml-1"%>
      <% end %>

        <div class="dropdown-menu bg-dark mt-0" aria-labelledby="profileDropdown">
          <% if user_signed_in? %>
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item"%>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item"%>
          <% else %>
            <%= link_to "Log in", new_user_session_path, class: "dropdown-item"%>
          <% end %>
        </div>
    </div>
  </div>
</nav>

app/views/shared/_signup.html.erb
<div class="modal fade" id="signupModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" >
  <div class="modal-dialog" style="height: 88vh">
    <div class="modal-content">
      <div class="modal-header d-block text-center">
        <img src="https://img.icons8.com/fluent/48/000000/google-logo.png" />
        <h2> <strong>Welcome to NomadConnect</strong></h2>
        <h5 class="modal-title mb-3" id="exampleModalLabel">Find new friends</h5>
        <%= link_to "Sign up with NomadConnect", new_user_registration_path, class: "sign-up-btn" %>

      </div>
      <div class="modal-body">
        <div class="links-container doc-content">
          <div class="or-word">
            <strong>OR</strong>
          </div>
          <%= link_to user_facebook_omniauth_authorize_path do  %>
          <div class="facebook-button d-flex link-btn">
            <i class="fab fa-facebook-f"></i>
            <p>Signup with FaceBook</p>
          </div>
          <% end %>
          <% if current_user %>
          <%= link_to user_google_oauth2_omniauth_authorize_path(user_id: current_user.id) do %>
          <div class="google-button d-flex link-btn">
            <img src="https://img.icons8.com/fluent/48/000000/google-logo.png" />
            <p>Signup with Google</p>
          </div>
          <% end %>
          <% else  %>
          <%= link_to user_google_oauth2_omniauth_authorize_path do %>
          <div class="google-button d-flex link-btn">
            <img src="https://img.icons8.com/fluent/48/000000/google-logo.png" />
            <p>Signup with Google</p>
          </div>
          <% end %>
          <% end %>
          <%= link_to user_github_omniauth_authorize_path do %>
          <div class="github-button d-flex link-btn">
            <i class="fab fa-github"></i>
            <p>Signup with GitHub</p>
          </div>
          <% end %>
        </div>
        <div class="modal-footer">

        </div>
      </div>
    </div>
  </div>

app/views/shared/_social.html.erb
<%= simple_form_for user do |f| %>
<%= f.input field  %>
<% end %>

app/views/shared/_weather.html.erb
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-12 col-md-4 col-sm-12 col-xs-12">
            <div class="card-weather p-4">
                <div class="d-flex mt-2">
                    <h4 class="flex-grow-1">Local Time: </h4>          
                    <h4><%= @weather_time.split[1] %></h4> 
                </div>
                <div class="d-flex flex-column temp">
                    <%=@weather_results[:condtion] %> 
                    <h1 class="mb-0 font-weight-bold" id="heading"> <%= @weather_results[:temp_c].to_i %> °</h1> 
                </div>
                <div class="d-flex">
                    <div class="temp-details flex-grow-1">
                        <p class="my-1"> <img src="https://i.imgur.com/B9kqOzp.png" height="17px"> <%= @weather_results[:wind_dir] %> at <%= @weather_results[:wind_kph]  %> kph </p>
                        <p class="my-1"> <i class="fa fa-tint mr-2" aria-hidden="true"></i> <%= @weather_results[:humidity] %>%  </p>
                        <p class="my-1"> <img src="https://i.imgur.com/wGSJ8C5.png" height="17px"> <%= @weather_results[:feelslike_c] %>° </p>
                    </div>
                    <div> <img src="https://<%=@weather_condition_icon%>" class="weather-icon"> </div>
                </div>
            </div>
        </div>
    </div>
</div>