config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" }
  resources :users, only: %w[index show update ]

  root to: 'cities#home'

  resources :cities, only: %w[new create edit update]
  resources :cities, only: %w[show] do 
    resources :events, only: %w[index new create]
    resources :faq, only: %w[index]
    resources :events, only: %w[index show]
    resources :headlines, only: %w[index]
    resources :chatrooms, only: :show
    resources :forums, only: %w[] do 
      resources :posts, only: %w[index]
    end 
  end
  resources :forums, only: [] do 
    resources :posts, only: %w[create]
  end 
  resources :posts, only: %w[destroy] do 
    resources :comments, only: %w[create]
  end 
  resources :chatrooms, only: [] do
    resources :messages, only: %w[create]
  end 
  resources :locations, only: %w[index]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :city

  def google_event
    Google::Apis::CalendarV3::Event.new(
      summary: summary,
      location: location,
      description: description,
      start: {
        date_time: start_date.to_datetime.rfc3339,
        time_zone: "Asia/Kolkata"
      },
      end: {
        date_time: end_date.to_datetime.rfc3339,
        time_zone: "Asia/Kolkata"
      }, 
      anyoneCanAddSelf: true
    )
  end 
end

app/controllers/events_controller.rb
require "google/apis/calendar_v3"
require "google/api_client/client_secrets.rb"
require 'googleauth'
require 'google_calendar'
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index 
    @city = City.find(params[:city_id])
  end 

  def new
    @event = Event.new
    @city = City.find(params[:city_id])
  end
  
  def create
    @city = City.find(params[:city_id])
    @event = Event.new(event_params)
    @event.user = current_user
    @event.city = @city
    if @event.save
      GoogleCalendar.api.insert_event(@city.calendar_id, @event.google_event)
      flash[:notice] = 'Task was successfully added.'
      redirect_to city_events_path
    else 
      render :new 
    end 
  end 

  private 

  def event_params
    params.require(:event).permit(:summary, :location, :description, :start_date, :end_date)
  end
end 

app/views/events/index.html.erb
<div class="events-page">
  <h1 class="display-4 text-center event-title"> <strong><%= @city.name %> Events </strong></h1>

  <div class="container d-flex">
    <div class="col-8">
      <iframe class="calendar" src="https://calendar.google.com/calendar/embed?src=<%=@city.calendar_id%>&=America%2FNew_York" style="border: 0" width="700" height="500" frameborder="0" scrolpng="no"></iframe>
    </div>

    <section class="events-holder col-4">
      <div class="col-8">
      </div>

      <h2 class="mb-4">Upcoming Events</h2>

      <% @city.events.order(:start_date).each do |event| %>
        <% if event.start_date > DateTime.current %>
          <div class="single-event">
            <p><%= event.summary %></p>
            <div class="d-flex">
              <p><%= event.start_date.strftime("%b %d, %Y-%I:%M %P ") %></p><p>  &nbsp <%= event.location %></p>
            </div>
          </div>
        <% end %>
      <% end %>

      <div class="single-event event-new">
        <%= link_to "Add new event",  new_city_event_path(@city), class: "btn btn-dark d-block mx-auto mt-2 mb-2 add-btn" %> 
      </div>
    </div>
  </section>
</div>

app/views/events/new.html.erb
<div class="new-event">
  <div class="event-form-container" style="height: 78vh">
    <%= simple_form_for [@city, @event] do |f| %>
    <div class="field">
      <%= f.input :summary %>
    </div>

    <div class="field">
      <%= f.input :description %>
    </div>

    <div class="field">
      <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"}, placeholder: 'Select Date...' %>
    </div>

    <div class="field">
      <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"}, placeholder: 'Select Date...'  %>
    </div>

    <div class="field">
      <%= f.input :location %>
    </div>

    <div class="actions">
      <%= f.submit"Create Event", class: "btn btn-dark"%>
    </div>
    <% end %>
  </div>
</div>