config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" }
  resources :users, only: %w[index show update ]

  root to: 'cities#home'

  resources :cities, only: %w[new create edit update]
  resources :cities, only: %w[show] do 
    resources :events, only: %w[index new create]
    resources :faq, only: %w[index]
    resources :events, only: %w[index show]
    resources :headlines, only: %w[index]
    resources :chatrooms, only: :show
    resources :forums, only: %w[] do 
      resources :posts, only: %w[index]
    end 
  end
  resources :forums, only: [] do 
    resources :posts, only: %w[create]
  end 
  resources :posts, only: %w[destroy] do 
    resources :comments, only: %w[create]
  end 
  resources :chatrooms, only: [] do
    resources :messages, only: %w[create]
  end 
  resources :locations, only: %w[index]
end

app/models/city.rb
# require 'google_calendar'
# require "google/apis/calendar_v3"
class City < ApplicationRecord
  # after_create :create_calendar
  has_many :forums
  has_many :locations
  has_many :users, through: :locations
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
  has_many :events

#   def create_calendar 
#     calendar = Google::Apis::CalendarV3::Calendar.new(summary: "NomadConnect-#{name} calendar", time_zone: 'America/Los_Angeles')
#     response = GoogleCalendar.api.insert_calendar(calendar)
#     update(calendar_id: response.id)
#     rule = Google::Apis::CalendarV3::AclRule.new(
#       scope: {
#         type: 'default'
#       },
#       role: 'reader'
#     )
#     GoogleCalendar.api.insert_acl(response.id, rule)
# end

end 

app/controllers/cities_controller.rb
require 'uri'
require 'net/http'
require 'openssl'
class CitiesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
    @city_name = @city.name

    url = URI("https://weatherapi-com.p.rapidapi.com/forecast.json?q=#{@city_name}&days=3")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Get.new(url)
    request["x-rapidapi-key"] = ENV['X_RAPIDAPI_KEY']
    request["x-rapidapi-host"] = 'weatherapi-com.p.rapidapi.com'

    response = http.request(request)
    jsonhash = JSON.parse(response.read_body).deep_symbolize_keys
    @weather_results = jsonhash[:current]
    @weather_time = jsonhash[:location][:localtime]
    @weather_condition_icon = @weather_results[:condition][:icon][2..-1]
  end

  def edit
    @city = City.find(params[:id])
  end

  def update
    @city = City.find(params[:id])
    @city.update(city_params)
    redirect_to city_path(@city)
  end

  private

  def city_params
    params.require(:city).permit(:name, :photo)
  end
end

app/views/cities/edit.html.erb
<div class="container">
<%= simple_form_for [@city]  do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/cities/home.html.erb
<div class="content">
  <%=cl_video_tag "video_eilxor", loop: true, autoplay: true, class: "wrapper home-video"%>
  <h1 class="nomad-title">NomadConnect</h1>
</div>

<div class="container">
<h1 class="text-center cities-title"><strong class="connect">Connect</strong> With People</h1>
<h2 class="text-center cities-sub-title">Anywhere</h2>
  <section class="cities">
    <% @cities.each do |city| %>
      <%= link_to city_path(city) do %>
        <div class="card-city" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path city.photo_key, height:300, width:300 %>)">
          <%= city.name %>
        </div>
      <% end %>
    <% end %>
  </section>
</div>

app/views/cities/new.html.erb
<div class="container">
<%= simple_form_for [@city]  do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/cities/show.html.erb
  
  <div class="img-container">
    <%= cl_image_tag @city.photo_key, class: "img-show-city"%>
    <h1 class="text-center main-title"><%= @city.name %></h1>
    <%= render partial: "shared/weather", locals: {weather_results: @weather_results, city_name: @city_name} %>
  </div>

  <div class="container mb-5">
    <section class="features">
      <%= link_to city_forum_posts_path(@city, @city.forums.first) do %>
        <div class="card-feature" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1487537023671-8dce1a785863?ixid=MXwxMjA3fDB8MHxzZWFyY2h8M3x8cG9kY2FzdHxlbnwwfDB8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60)">
          Discussion
        </div>
      <% end %>
      
      <%= link_to city_headlines_path(@city) do %>
        <div class="card-feature" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1523120974498-9d764390d8e5?ixid=MXwxMjA3fDB8MHxzZWFyY2h8OHx8dHlwaW5nJTIwbWFjaGluZXxlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60)">
          Local News
        </div>
      <% end %>
      <%= link_to city_events_path(@city) do %>
        <div class="card-feature" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1611302457661-d24c21494f2a?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjJ8fGNhbGVuZGFyfGVufDB8MHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60)">
          Events
        </div>
      <% end %>

      <%= link_to city_faq_index_path(@city) do %>
        <div class="card-feature" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1512314889357-e157c22f938d?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8aWRlYXxlbnwwfDB8MHw%3D&auto=format&fit=crop&w=500&q=60)">
          FAQ
        </div>
      <% end %>
    </section>
  </div>